### PR TITLE
fix(legacy-html): convert entry.changes to html

### LINKED ISSUE #326: `entry.changes` aren't converted to HTML
Image

As shown in the screenshot above, the `legacy-html` generator does not convert the markdown changes to their HTML equalivalent.

### PR DESCRIPTION
**Pull request by araujogui**
## Description

Fix conversion of entry.changes to HTML.

## Validation
image

## Related Issues

Fixes #326 

### Check List

- [x] I have read the [Contributing Guidelines](https://github.com/nodejs/api-docs-tooling/blob/main/CONTRIBUTING.md) and made commit messages that follow the guideline.
- [x] I have run `node --run test` and all tests passed.
- [x] I have check code formatting with `node --run format` & `node --run lint`.
- [x] I've covered new added functionality with unit tests if necessary.

### CODE REVIEW

File: src/generators/legacy-html/utils/buildContent.mjs [hunk 1]
```diff
@@ -76,13 +77,38 @@ const buildHtmlTypeLink = node => {
...
+ * @param {import('unified').Processor} remark
+ */
+const createHistoryTableRow = (
+  { version: changeVersions, description },
+  remark
+) => {
+  const descriptionNode = remark.parse(description);
+
+  // Convert node to hast to make it compatible with createElement
+  const descriptionHast = toHast(descriptionNode);
```
Comment (avivkeller) [inline src/generators/legacy-html/utils/buildContent.mjs:93]: If we leave it as Mdast, won't it get converted to Hast in a later stage, or has that already occured?

**Comment by avivkeller** [comment]
> image

OoC, may I ask what the second version is?

**Comment by avivkeller** [comment]
No problem, I thought it was funny 🤭

**Review by flakey5 — APPROVED** [review]
